export default {
  apellidoPaterno: 'Apellido Paterno',
  apellidoMaterno: 'Apellido Materno',
  nombres: 'Nombres',
  nacionalidad: 'Nacionalidad',
  tipoDocumento: 'Tipo de Documento',
  nroDocumento: 'Nro. de Documento',
  tlfFijo: 'Número telefónico',
  tlfCelular: 'Número de celular',
  email: 'Correo electrónico',
  mayorGradoAcademico: 'Mayor Grado Académico',
  paisMayorGradoAcademico: 'País de Mayor Grado Académico',
  mencionMayorGradoAcademico: 'Mención del Mayor Grado Académico',
  universidadMayorGradoAcademico: 'Universidad del Mayor Grado Académico',
  fechaIngreso: 'Fecha de Ingreso',
  docenteLey30220: 'Docente durante ley 30220',
  dictaPregrado: 'Dicta Pregrado',
  dictaMaestria: 'Dicta Maestría',
  dictaDoctorado: 'Dicta Doctorado',
  dictaDiplomatura: 'Dicta diplomatura',
  categoriaDocente: 'Categoría Docente',
  dedicacion: 'Nivel de dedicación',
  horasSemanalesClase: 'Horas de clases semanales',
  horasSemanalesOtros: 'Horas de otras actividades semanales',
  docenteInvestigador: 'Docente Investigador',
  registradoDINA: 'Registrado en DINA',
  registradoREGINA: 'Registrado en REGINA',
  grupoInvestigacion: 'Grupo de Investigación',
  condicionGrupoInvestigacion: 'Condición Grupo de Investigación'
};